num = [2,5,1,6,4]
print(num)
num.append(9)
print(num)
num.insert(2,10)
print(num)
num.remove(1)
print(num)
if 14 in num:
    n = num.remove(14)
    print(n)
last = num.pop()
print(last,num)
index = num.index(4)
if 22 in num:
    index = num.index(22)
    print(num)
print(index)
c = num.count(5)
print(c)
num.sort()
print(num)
num.reverse()
print(num)
